### ISSUE TITLE
Link to API reference

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/checkout-sdk-php#13]
The link to the documentation in the wiki is broken:
https://github.com/checkout/checkout-sdk-php/wiki/2.-Payments#request-a-payment

The "documentation" link on this page should point to:
https://api-reference.checkout.com/#tag/Payments

**Comment by david-fiaty-cko** [comment]
Also, the last link  of the page is broken here: https://github.com/checkout/checkout-sdk-php/wiki/1.-Tokens

**Comment by aquila-freitas-cko** [comment]
Hi @david-fiaty-cko ,
I have reviewed the links the wiki and updated all the broken ones.
