### ISSUE TITLE
Example to attach email address to payments

### ISSUE THREAD

**Issue by lululombard** [checkout/checkout-sdk-php#14]
Hi,
I'm trying to use this SDK on a personal project, but when I charge a card, there's no obvious way to attach an email and in the sandbox console, I see emails like `ggfdad6afgg675gfd@auto.cko`. I read the wiki I could not find anything. Can someone update the wiki with a really basic example under the payments section?
Thanks.

**Comment by aquila-freitas-cko** [comment]
Hello,
Sorry, this kind of documentation it's on Checkout's[website](https://docs.checkout.com/docs/). The email you see is generated by Checkout's API when you request a payment without customer details. We will associate the payment used to that customer, this way you make Payments with CustomerSource.
You can save a customer yourself by:
```php
$customer = new Models\Payments\Customer();
$customer->email = 'your@email.com';
$customer->name = 'Name Surname';
$payment->customer = $customer
```

**Comment by aquila-freitas-cko** [comment]
I am closing this issue, please reopen if it need further explanations.
