### ISSUE TITLE
Error "Call to a member function getId() on array" when calling Payment's getSourceId()

### ISSUE THREAD

**Issue by mwalves** [checkout/checkout-sdk-php#148]
### Environment

* Checkout SDK version: 1.0.20
* Platform and version: 
* Operating System and version: Linux

### Description

After upgrading from 1.0.19 to 1.0.20 we started getting an error when calling the method `getSourceId()` on the response of the method `details()`.

Error detail from our log:
```
{"exception":{"class":"Error","message":"Call to a member function getId() on array","code":0,"file":"/var/www/html/vendor/checkout/checkout-sdk-php/src/Models/Payments/Payment.php:207"}}
```

After analyzing the diff it seems the code introduced by version 1.0.20 introduced a bug with the changes for `src/Models/Payments/Payment.php` method `getSourceId()`.

Within the method `getSourceId()`, when the `$source` is an `array` but has no `id` set on it, the code will fallback to the `elseif` block and will try to call `$source->getId()` on an `array`, causing the mentioned error.

### Expected behavior

Method `getSourceId()` returns the source id or empty string as per 1.0.19 version.

### Current behavior

Exception is thrown.

```
{"exception":{"class":"Error","message":"Call to a member function getId() on array","code":0,"file":"/var/www/html/vendor/checkout/checkout-sdk-php/src/Models/Payments/Payment.php:207"}}
```

### Steps to reproduce

We could not identify a pattern of transactions that causes the error as we got it from some samples on our production integration.  

Although not all transactions are presenting this error, all cases identified were related to transactions which 3DS authentication was requested.

A possible way to reproduce:
* Send transaction that requires 3DS authentication
* Poll method `details()` for the transaction in order to identify the transaction status (Authorized, Declined, or still Pending).

### Possible solution

- [ ] I may be able to implement this bug fix

**Comment by Dogpound23** [comment]
Need help

**Comment by Dogpound23** [comment]
#147

**Comment by Dogpound23** [comment]
G

**Comment by Armando-Ibarra** [comment]
@mwalves Sorry for miss this.
I see, this is a problem using legacy versions, a lot of things on the response changed, let me fix and double check this, will have a solution later today.

**Comment by Armando-Ibarra** [comment]
Will release today
#149
