### ISSUE TITLE
Monolog v3 is not supported

### ISSUE THREAD

**Issue by yagizpf** [checkout/checkout-sdk-php#178]
### Environment

* Checkout SDK version: 3.0.5
* Platform and version:
* Operating System and version:

### Expected behavior
It should be working with Monolog 3.

### Current behavior
The current sdk doesn't support Monolog v3 and it is impossible to use it when using latest Monolog version.

### Steps to reproduce
1. Install Monolog >v3 into a composer project
2. Try installing checkout-sdk-php on top of that and it will fail because of dependency mismatch.

### Possible solution
Adding Monolog 3 support to checkout-php-sdk.

**Comment by Armando-Ibarra** [comment]
New version is available thought #180 , let us know if you have some questions
