### ISSUE TITLE
invalid public key

### ISSUE THREAD

**Issue by ronnycoolen** [checkout/checkout-sdk-php#191]
I get the message 'invalid public key' when I try to use a production key provided by Checkout.

It seems there are dashes (-) in the key, and the SDK flags these as invalid.

My public key has this form:
`pk_abcdabcd-abcd-abcd-abcd-abcdabcdabcd`
where abcd are hexadecimal values.

The secret key has the same problem.

**Comment by Armando-Ibarra** [comment]
Hi @ronnycoolen your key matches for previous version, so you need to initialize the SDK as follows
`$checkoutApi = CheckoutSdk::builder()
                    ->previous()
                    ->staticKeys()
                    ->environment(Environment::sandbox()) // or production()
                    ->publicKey("public_key") // optional, only required for operations related with tokens
                    ->secretKey("secret_key")
                    ->build();`

All is explained on the README. let us know if you have more issues.

**Comment by ronnycoolen** [comment]
Thank you for your response. I assumed incorrectly the public keys were keys for the current version.
