### ISSUE TITLE
Upgrade guides

### ISSUE THREAD

**Issue by Bird87ZA** [checkout/checkout-sdk-php#213]
I am working for a company that still uses v1 of the PHP SDK.

I am now in the process of upgrading to v3, but I'm having a hard time, due to significant changes in the SDK.

Is there some place where I can see upgrade guides from v1 -> v2 -> v3?

**Comment by Bird87ZA** [comment]
The documentation isn't very helpful. We have, for instance, something like this:

```
    public function createTrackingId(\Checkout\Library\Model $model): string
    {
        $trackingId = $model->getId();
        $actionId = $model->getActionId();
        if ($actionId) {
            $trackingId .= "-$actionId";
        }

        return $trackingId;
    }
```

`Checkout\Library\Model` nor `Checkout\Models\Payments\Payment` (what we are trying to get ID and ActionID on) does not exist in v2 or v3 of the SDK. There is no mention in the documentation on where it went, how to integrate with the new SDK or how to get the Id or ActionId.

Do you have any pointers on how we can migrate?

**Comment by armando-rodriguez-cko** [comment]
Hi @Bird87ZA! Do you have more questions? If not, we will close this issue, please if you need it, open new issues please. Thank you.
