### ISSUE TITLE
php  request a payment ,but reurn :The API response status code (422) does not indicate success.

### ISSUE THREAD

**Issue by helloworld-1988** [checkout/checkout-sdk-php#215]
**Here is my code:**

$CheckoutAPI = CheckoutSdk::builder()->staticKeys()
    ->publicKey(("pk_sbox_aztjtmbsxh4eu2t2rgjsqho3auj"))
    ->secretKey('sk_sbox_qmlezzgfjt6th4tjkgjvidqyyu=')
        ->environment(Environment::sandbox())
    ->build();

$requestTokenSource = new RequestTokenSource();
$requestTokenSource->token = 'tok_jmmtsp3zhxsezo3th634nro4m4';
$requestTokenSource->type='token';

$customerRequest = new CustomerRequest();
$customerRequest->email = '111@qq.com';

$paymentInstrumentSender = new PaymentInstrumentSender();

$paymentRequest = new PaymentRequest();//pc_ir6xspfme4ce5he7snfb5ggzxq
$paymentRequest->source = $requestTokenSource;
$paymentRequest->capture = true;
$paymentRequest->reference = uniqid();
//  $paymentRequest->success_url = "https://testing.checkout.com/sucess";
//        $paymentRequest->failure_url = "https://testing.checkout.com/failure";
$paymentRequest->amount = 19;
$paymentRequest->currency = 'USD';
$paymentRequest->customer = $customerRequest;
try {

$response = $CheckoutAPI->getPaymentsClient()->requestPayment( $paymentRequest);
  print_r($response );exit;
} catch(Exception $ex) {
    print_r($ex->getMessage());
}
exit;

**these code throw a exception:**
The API response status code (422) does not indicate success.

Can anybody  help me ?

**Comment by Rahmat-Vigorous** [comment]
Try with curl request. This is working.

$apiUrl = 'https://api.sandbox.checkout.com/payments';
        // Payment data
        $paymentData = [
            'source' => [
                'type' => 'token',
                'token' => 'tok_362o6ajrrybeln7ep5lw67ujh4', // Replace with your actual token
            ],
            'amount' => 10000,
            'currency' => 'USD',
            'processing_channel_id' => 'pc_d3wbd3opokeu5lrvryllgjhdnk', // Replace with your actual processing channel ID
            'reference' => 'ORD-5023-4E89',
            'metadata' => [
                'udf1' => 'TEST123',
                'coupon_code' => 'NY2018',
                'partner_id' => 123989,
            ],
        ];
        
        try {
            // Initialize cURL
            $ch = curl_init($apiUrl);

            // Set cURL options
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');
            curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($paymentData));
            curl_setopt($ch, CURLOPT_HTTPHEADER, [
                'Content-Type: application/json',
                'Accept: application/json',
                'Authorization: Bearer ' . $secretKey,
            ]);
        
            // Execute cURL request
            $response = curl_exec($ch);

            // Check for cURL errors
            if ($response === false) {
                throw new \Exception(curl_error($ch), curl_errno($ch));
            }
        
            // Close cURL
            curl_close($ch);
            return $response;
        } catch (\Exception $e) {
            return 'cURL Error: ' . $e->getMessage();
        }

**Comment by armando-rodriguez-cko** [comment]
Hello @helloworld-1988! Thank you for your comments.
We found a bug in your code, you have unnecessary parentheses in the public key, and you probably need to use a processing channel id in your request if you have more than one in the same API key.
The 422 error means that you have a malformed request error in your request.
Please review your code and let us know if it fixed your bug or if you need more help.

**Comment by armando-rodriguez-cko** [comment]
We closed this issue due to its inactivity.
