### ISSUE TITLE
https://github.com/checkout/checkout-sdk-php  Library not installed by composer update.

### ISSUE THREAD

**Issue by GithubGur** [checkout/checkout-sdk-php#216]
https://github.com/checkout/checkout-sdk-php  Library not installed by composer update.

### Environment

* 3.0.13:
* Php (7.4):
* window 10:

### Description

version mismatch

**Comment by armando-rodriguez-cko** [comment]
Hi @GithubGur, can you share your composer version with us?

**Comment by GithubGur** [comment]
composer version : 1.6.3

**Comment by GithubGur** [comment]
> Hi @GithubGur, can you share your composer version with us?

composer version : 1.6.3

**Comment by armando-rodriguez-cko** [comment]
Thank you @GithubGur. We are reviewing it.

**Comment by GithubGur** [comment]
Any update ??
________________________________

**Comment by armando-rodriguez-cko** [comment]
Hello @GithubGur, probably is a problem cache from the repo.packagist.org, can you connect by VPN from other country different than yours and check if the problem persist?

Other solution is to do a clean installation of the package and/or update composer.
You can try this:
`composer upgrade`
`composer clearcache`
`composer require checkout/checkout-sdk-php:3.0.14`

Check this URL: https://getcomposer.org/doc/01-basic-usage.md, review the file `composer.lock`, we can find:

> ...Either way, running install when a composer.lock file is present resolves and installs all dependencies that you listed in composer.json, but Composer uses the exact versions listed in composer.lock to ensure that the package versions are consistent for everyone working on your project...

Please if the problem doesn't fix, contact us again and we will look for more solutions.

Thank you.

**Comment by armando-rodriguez-cko** [comment]
Hi @GithubGur! Has your problem been resolved?

**Comment by armando-rodriguez-cko** [comment]
Hi @GithubGur, if you don't have more questions, we will close the issue. Thank you.
