### ISSUE TITLE
Guzzle timeout or custom guzzle client

### ISSUE THREAD

**Issue by naliferov** [checkout/checkout-sdk-php#228]
Hi!

Could you please implement ability to set timeout of requests to your API or ability to use custom Guzzle client? Because in case your service is going down, this will hang php-fpm on our side. This already happen once.

I see that you have ability to replace HttpClientBuilder:
```
public function httpClientBuilder(HttpClientBuilderInterface $httpClientBuilder)
    {
        $this->httpClientBuilder = $httpClientBuilder;
        return $this;
    }
```
Maybe it's would be even better if you add some default timeout. For example 60 seconds.

**Comment by armando-rodriguez-cko** [comment]
Thank you @naliferov! we will take a look soon.
