### ISSUE TITLE
Call to a member function getBody() on null

### ISSUE THREAD

**Issue by parkhomenko-pp** [checkout/checkout-sdk-php#239]
### Description
RequestException::getResponse function ALWAYS (vendor/guzzlehttp/guzzle/src/Exception/ConnectException.php) return a null value when the request fails.

### Possible solution
```php
<?php

namespace Checkout;

use GuzzleHttp\Exception\RequestException;

class CheckoutApiException extends CheckoutException
{
    /**
     * @var array
     */
    public $error_details;
    /**
     * @var HttpMetadata
     */
    public $http_metadata;

    /**
     * @param RequestException $requestException
     * @return CheckoutApiException
     */
    public static function from(RequestException $requestException)
    {
        $response = $requestException->getResponse();

        $ex = new CheckoutApiException(sprintf(
            "The API response status code (%s) does not indicate success.",
            $requestException->getCode()
        ));
        $ex->error_details = isset($response) ? json_decode($response->getBody()->getContents(), true) : [];;
        $ex->http_metadata = CheckoutUtils::getHttpMetadata($response);
        return $ex;
    }
}

```

### Additional information
Error: Call to a member function getBody() on null
- /vendor/checkout/checkout-sdk-php/lib/Checkout/CheckoutApiException.php(24): Checkout\CheckoutApiException::from
- /vendor/checkout/checkout-sdk-php/lib/Checkout/ApiClient.php(192): Checkout\ApiClient::invoke
- /vendor/checkout/checkout-sdk-php/lib/Checkout/ApiClient.php(54): Checkout\ApiClient::post
- /vendor/checkout/checkout-sdk-php/lib/Checkout/Payments/Hosted/HostedPaymentsClient.php(38): Checkout\Payments\Hosted\HostedPaymentsClient::createHostedPaymentsPageSession

**Comment by armando-rodriguez-cko** [comment]
Thank you @parkhomenko-pp! We will implement it in the next release, do you want to propose a PR with your changes?

**Comment by parkhomenko-pp** [comment]
@armando-rodriguez-cko https://github.com/checkout/checkout-sdk-php/pull/240

**Comment by parkhomenko-pp** [comment]
@armando-rodriguez-cko https://github.com/checkout/checkout-sdk-php/pull/241
