### ISSUE TITLE
ConnectException not managed if the host is down

### ISSUE THREAD

**Issue by benschumi** [checkout/checkout-sdk-php#242]
### Environment

* Checkout SDK version: 3.0.21
* Platform and version: PHP 7.1
* Operating System and version: MacOs 14.2.1
* 

### Description

While integrating paypal, i try to simulate a case where the host api.sandbox.checkout.com is down by putting an unreachable ip in the host file.
I want to manage the case if checkout is down, the call for a paymentRequest should not impact our payment page.
The execption is a GuzzleHttp\Exception\ConnectException but there is an error in the CheckoutApiException file

### Expected behavior

The invoke method in ApiClient should return a CheckoutApiException 

### Current behavior

A FatalThrowableError from the method from in CheckoutApiException.

The response is null in a ConnectException 

````
ConnectException {#4544 ▼
  -request: Request {[#4547 ▶](https://mywebsite.com)}
  -response: null
  -handlerContext: array:30 [▶]
  #message: "cURL error 7: Failed to connect to api.sandbox.checkout.com port 443: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)"
  #code: 0
  #file: "/srv/app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php"
  #line: 200
  trace: {▶}
}
````

Error on Class CheckoutApiException (line 25)
Call to a member function getBody() on null

````    
public static function from(RequestException $requestException)    
{               
     $body = json_decode($requestException->getResponse()->getBody()->getContents(), true);        
     $ex = new CheckoutApiException(sprintf(            
         "The API response status code (%s) does not indicate success.",            
...

````

### Steps to reproduce

put 0.0.0.0 on the host api.sandbox.checkout.com on host file

### Possible solution

Just manage differently the ConnectException in class CheckoutApiException

**Comment by armando-rodriguez-cko** [comment]
Thank you @benschumi! Thank you. We have improvement to release to improve this point.

**Comment by armando-rodriguez-cko** [comment]
I hope the new release https://github.com/checkout/checkout-sdk-php/releases/tag/3.1.0 help you

**Comment by benschumi** [comment]
Perfect, thank you @armando-rodriguez-cko
