### ISSUE TITLE
invalid public key

### ISSUE THREAD

**Issue by sharafdglab** [checkout/checkout-sdk-php#266]
I have an integration with checkout.com using this sdk, and suddenly in the 20th august 2024, it stopped working.

We are doing refunds, and it is succeeding, but when we try to get actions to get the ARN, it complains about invalid public key.

It was working for a year now, suddenly it started to complain, we are using the new checkout dashboard.

anything changed since 20 august 2024 ?

**Comment by armando-rodriguez-cko** [comment]
Hi @sharafdglab, please contact with [support@checkout.com](mailto:support@checkout.com)

**Comment by armando-rodriguez-cko** [comment]
Hi @sharafdglab, we hope your issue has been resolved. We are proceeding to close it due to inactivity. If there is any news, please create a new issue again. Thank you.
