### ISSUE TITLE
Update unit tests.

### ISSUE THREAD

**Issue by aquila-freitas-cko** [checkout/checkout-sdk-php#27]
Unit tests hasn't been updated for a while.

**Comment by rsaestrela** [comment]
Hi @aquila-freitas-cko. We've just updated the codebase and released version 2.0.0-beta3 that contains an extended suite of unit and integration tests. Continuous integration with GitHub Actions is running them on every pull request, merge to master and release workflows. In case you have any questions feel free to open a new issue. Thanks!
