### ISSUE TITLE
Please provide authentication parameter in payment request

### ISSUE THREAD

**Issue by JZds** [checkout/checkout-sdk-php#273]
According to documentation: 
https://api-reference.checkout.com/#operation/requestAPaymentOrPayout!path=0/authentication/preferred_experiences&t=request

Authentication parameter is missing in this SDK. Cannot create pull requests myself, created a patch instead.

Thank you.

[Authentication_in_payment_request.patch](https://github.com/user-attachments/files/17777075/Authentication_in_payment_request.patch)

**Comment by armando-rodriguez-cko** [comment]
Thank you @JZds. I will review it.
You can fork the project and create a PR from your fork
