### ISSUE TITLE
Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by eventhorizonpl** [checkout/checkout-sdk-php#29]
Hi,

I'm working on integration of Checkout.com in our project. While trying to fetch a list of events I noticed this bug

`In Event.php line 88:

  [Symfony\Component\Debug\Exception\ContextErrorException]
  Warning: Invalid argument supplied for foreach()

Exception trace:
 () at /home/michal/projects/somtel-api/vendor/checkout/checkout-sdk-php/src/Models/Events/Event.php:88
 Checkout\Models\Events\Event::create() at /home/michal/projects/somtel-api/vendor/checkout/checkout-sdk-php/src/Library/Model.php:95
 Checkout\Library\Model::arrayToModel() at /home/michal/projects/somtel-api/vendor/checkout/checkout-sdk-php/src/Models/Events/Event.php:108
 Checkout\Models\Events\Event::arrayToModel() at /home/michal/projects/somtel-api/vendor/checkout/checkout-sdk-php/src/Library/Model.php:84
 Checkout\Library\Model::load() at /home/michal/projects/somtel-api/vendor/checkout/checkout-sdk-php/src/Library/Controller.php:93
 Checkout\Library\Controller->response() at /home/michal/projects/somtel-api/vendor/checkout/checkout-sdk-php/src/Controllers/EventController.php:94
 Checkout\Controllers\EventController->retrieve() at /home/michal/projects/somtel-api/src/RemitBundle/Service/CheckoutComService.php:60
`

I guess it's related to a fact that we might not have any events yet.

Best regards,
Michal

**Comment by aquila-freitas-cko** [comment]
Hi @eventhorizonpl ,
We were about to release a new version. I will look into it now, thank you for letting us know.

I will get back to you as soon as this issue is investigated and released a fix.

Kind Regards,
Áquila Freitas

**Comment by eventhorizonpl** [comment]
@aquila-freitas-cko 

Hi. Thank you for the fix. Can you also update https://packagist.org/packages/checkout/checkout-sdk-php ?
