### ISSUE TITLE
Replace logging by package like monolog

### ISSUE THREAD

**Issue by toooni** [checkout/checkout-sdk-php#3]
I think it's a critical issue to automatically log to the filesystem. For example, in my environment (symfony) it was just writing logs in the "web/" directory which is public.
The logging should be replaced by the a standard php-fig solution defined in (https://github.com/php-fig/log). Most commonly https://github.com/Seldaek/monolog.

**Comment by aquila-freitas-cko** [comment]
Hi @toooni ,
You can always define the paths of the log files in the config.ini. I will look into PSR-FIG Log this week, thanks for the suggestion.

**Comment by aquila-freitas-cko** [comment]
Hello @toooni ,
It is in the pipeline to implement more advanced logging mechanisms. Meanwhile you can set a custom path in the configuration or switch it off.

`
[logs]
logging = true
request = "/var/log/sdk_request.log"
response = "/var/log/sdk_response.log"
error = "/var/log/sdk_error.log"
`
