### ISSUE TITLE
Capture and Refund doesn't return amount

### ISSUE THREAD

**Issue by eventhorizonpl** [checkout/checkout-sdk-php#31]
Hi,

It's not a big deal, but I noticed that when I create a payment and later I capture it and refund, both objects doesn't contain information about amount. When I check actions informations about amount are present

`
object(Checkout\Models\Response)#412 (2) {
  ["list"]=>
  array(3) {
    [0]=>
    object(Checkout\Models\Payments\Action)#374 (7) {
      ["id"]=>
      string(30) "act_hv4ewmdkvqwendhxstriktubhq"
      ["type"]=>
      string(6) "Refund"
      ["processed_on"]=>
      string(20) "2019-07-04T13:06:52Z"
      ["amount"]=>
      int(12345)
      ["approved"]=>
      bool(true)
      ["response_code"]=>
      string(5) "10000"
      ["response_summary"]=>
      string(8) "Approved"
    }
    [1]=>
    object(Checkout\Models\Payments\Action)#827 (8) {
      ["id"]=>
      string(30) "act_hi525gy7wscuhamnhwn7lacx7i"
      ["type"]=>
      string(7) "Capture"
      ["processed_on"]=>
      string(20) "2019-07-04T13:06:50Z"
      ["amount"]=>
      int(12345)
      ["approved"]=>
      bool(true)
      ["response_code"]=>
      string(5) "10000"
      ["response_summary"]=>
      string(8) "Approved"
      ["processing"]=>
      array(2) {
        ["acquirer_transaction_id"]=>
        string(10) "8138434673"
        ["acquirer_reference_number"]=>
        string(12) "000111280834"
      }
    }
    [2]=>
    object(Checkout\Models\Payments\Action)#414 (9) {
      ["id"]=>
      string(30) "act_le7hsxg37boehpksrupde5geju"
      ["type"]=>
      string(13) "Authorization"
      ["processed_on"]=>
      string(20) "2019-07-04T13:06:48Z"
      ["amount"]=>
      int(12345)
      ["approved"]=>
      bool(true)
      ["auth_code"]=>
      string(6) "078839"
      ["response_code"]=>
      string(5) "10000"
      ["response_summary"]=>
      string(8) "Approved"
      ["processing"]=>
      array(2) {
        ["acquirer_transaction_id"]=>
        string(10) "8138434669"
        ["retrieval_reference_number"]=>
        string(12) "000078839029"
      }
    }
  }
  ["http_code"]=>
  int(200)
}
`

Here is Refund
`
object(Checkout\Models\Payments\Refund)#793 (7) {
  ["id"]=>
  string(30) "pay_le7hsxg37boehpksrupde5geju"
  ["amount"]=>
  NULL
  ["reference"]=>
  string(0) ""
  ["metadata"]=>
  object(Checkout\Models\Payments\Metadata)#798 (0) {
  }
  ["action_id"]=>
  string(30) "act_hv4ewmdkvqwendhxstriktubhq"
  ["_links"]=>
  array(1) {
    ["payment"]=>
    array(1) {
      ["href"]=>
      string(72) "https://api.sandbox.checkout.com/payments/pay_le7hsxg37boehpksrupde5geju"
    }
  }
  ["http_code"]=>
  int(202)
}
`

Here is Capture
`
object(Checkout\Models\Payments\Capture)#799 (7) {
  ["id"]=>
  string(30) "pay_le7hsxg37boehpksrupde5geju"
  ["amount"]=>
  NULL
  ["reference"]=>
  string(0) ""
  ["metadata"]=>
  object(Checkout\Models\Payments\Metadata)#453 (0) {
  }
  ["action_id"]=>
  string(30) "act_hi525gy7wscuhamnhwn7lacx7i"
  ["_links"]=>
  array(1) {
    ["payment"]=>
    array(1) {
      ["href"]=>
      string(72) "https://api.sandbox.checkout.com/payments/pay_le7hsxg37boehpksrupde5geju"
    }
  }
  ["http_code"]=>
  int(202)
}

`

Best regards,
Michal

**Comment by aquila-freitas-cko** [comment]
Yes, I understand. Unfortunately that is not happening, the gateway doesn't return the amount in the response. My suggestion is to call the details (`$checkout->payments()->details($payID);`) for now.

**Comment by eventhorizonpl** [comment]
@aquila-freitas-cko ok, thanks for the suggestion.

**Comment by aquila-freitas-cko** [comment]
No worries. 👌
