### ISSUE TITLE
->events()->retrieve(); list count and total_count doesn't math

### ISSUE THREAD

**Issue by eventhorizonpl** [checkout/checkout-sdk-php#32]
Hi,

Small problem. I think it should math
[results.txt](https://github.com/checkout/checkout-sdk-php/files/3359550/results.txt)

`
object(Checkout\Models\Response)#792 (7) {
  ["list"]=>
  array(10) {
[..]
  ["total_count"]=>
  int(7)
`

Isn't it?

Best regards,
Michal

**Comment by aquila-freitas-cko** [comment]
Hey @eventhorizonpl , I believe you should contact support@checkout.com for this as this is related to you account.

**Comment by eventhorizonpl** [comment]
@aquila-freitas-cko thank you for the information, problem forwarded to support team

**Comment by aquila-freitas-cko** [comment]
No problem.
Just one tip, you can include query parameters by passing with a criteria ([full list](https://docs.checkout.com/docs/events-api#section-get-events-descending)).
E.g. $checkout->events()->retrieve(array('from' => '2019-01-04T13:47:16Z', 'to' => '2019-07-04T13:47:12Z'));
