### ISSUE TITLE
Checkout classic Api support

### ISSUE THREAD

**Issue by adil8531** [checkout/checkout-sdk-php#35]
Hi
   I would like to know if this package supports checkout's classic api also or just support checkout's v2 apis

Thanks

**Comment by david-fiaty-cko** [comment]
Hi @adil8531, this package supports only the Unified Payments API, which is Checkout.com's new API.
In order to use the Classic API, please have a look here: https://github.com/checkout/checkout-php-library

**Comment by adil8531** [comment]
Thanks for the answer.
