### ISSUE TITLE
PayPal payments

### ISSUE THREAD

**Issue by MrMooky** [checkout/checkout-sdk-php#36]
Your docs are REALLY slim when it comes to accepting PayPal payments. Is there any resource that describes how to implement PayPal payments with PHP in combination with checkout.com?

Do I need to use CURL, or can I use your PHP API? If the API, how?

**Comment by MrMooky** [comment]
My curl post looks like this:

```
$url = 'https://api.sandbox.checkout.com/payments';
$authKey = 'sk_test_12345xxx';

$data = array(
    'amount' => 500,
    'currency' => 'EUR',
    'source' => [
        'type' => 'paypal',
        'invoice_number' => '12345'
    ]
);

$data_string = json_encode($data);
$curl = curl_init($url);

curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "POST");

curl_setopt($curl, CURLOPT_HTTPHEADER, array(
    'Authorization: '.$authKey,
    'Content-Type: application/json',
));

curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl, CURLOPT_POSTFIELDS, $data_string);

$result = curl_exec($curl);
curl_close($curl);

var_dump($result);
```

Yet `var_dump` results in this:

`string(126) "{"request_id":"87e5510d-6696-45cd-a4e4-4f79140417bb","error_type":"validation_error","error_codes":["payment_method_invalid"]}"`

**Comment by aquila-freitas-cko** [comment]
Hi @MrMooky ,
PayPal hasn't been implemented to the PHP SDK yet, you can see here the list of supported alternative payment methods https://github.com/checkout/checkout-sdk-php/wiki/3.-Alternative-Payments .

You can use cURL according to the docs, but make sure you have PayPal enabled in your account.

**Comment by MrMooky** [comment]
@aquila-freitas-cko I wrote the support two days ago because I cannot enable PayPal myself in the Sandbox Hub – have not received feedback yet.

**Comment by aquila-freitas-cko** [comment]
Ok, I will close this issue. Next version of the SDK will include support for PayPay, I will let you know when it's released.

**Comment by inikoo** [comment]
Hello, has been more than 2 years and still not support for PayPal ?
