### ISSUE TITLE
Capture method only takes integer amounts. Incorrect amount reflecting in checkout.com dashboard

### ISSUE THREAD

**Issue by parekhreena** [checkout/checkout-sdk-php#38]
Hi,

I am trying to capture the amount from card programmatically. But it only seems to accept integer amounts. There will be instances where will need to charge amounts upto 2 decimal places. Which is also the default price format of magento. Also, the captured amount reflects incorrect in checkout.com dashboard. Here is the code:

```
 $additionalInformation = $payment->getAdditionalInformation();
        $invoiceId = $this->invoiceOrder->execute($orderId, false, $items, true);
        $invoice = $this->invoice->load($invoiceId);
        $storeCode = $this->storeManager->getStore($order->getStoreId())->getCode();
        $checkout = $this->checkoutcomService->init($storeCode);
        $payment = new \Checkout\Models\Payments\Capture($additionalInformation['transaction_info']['id']);
        $payment->amount = (int) $invoice->getGrandTotal();  //Output = 190
        $capture = $checkout->checkoutApi->payments()->capture($payment);
        return $invoiceId;
```
The class construct \Checkout\Models\Payments\Capture::__construct has typehint of amount as integer.
Checkout.com Dashboard shows captured amount as 1.90
and the response from checkout.com shows 190 as below: 

```
{
    "id": "<<event_id>>",
    "type": "payment_captured",
    "created_on": "2019-08-07T16:18:15Z",
    "data": {
        "action_id": "<<Action_Id>>",
        "response_code": "10000",
        "response_summary": "Approved",
        "amount": 190,
        "metadata": {
            "methodId": "checkoutcom_card_payment",
            "quoteData": "{\"quote_id\":\"<<quote_id>>\",\"store_id\":1,\"customer_email\":null}"
        },
        "processing": {
            "acquirer_transaction_id": "<<acq_trans>>",
            "acquirer_reference_number": "<<acq_ref>>"
        },
        "id": "<<payment_id>>",
        "currency": "AED",
        "processed_on": "2019-08-07T16:18:15Z",
        "reference": "<<my_reference>>"
    },
    "_links": {
        "self": {
            "href": "https://api.sandbox.checkout.com/events/<<event_id>>"
        },
        "payment": {
            "href": "https://api.sandbox.checkout.com/payments/<<my_id>>"
        }
    }
}
```

**Comment by david-fiaty-cko** [comment]
@parekhreena the API reference explains that the amount should be sent in cents.
So you should multiply the amount by 100 rather than casting to integer.

For example, in order to charge an amount of £19.55, you should sent 19.55* 100 to the gateway, which will be 1955.

**Comment by parekhreena** [comment]
Hello David, 

The API Reference only has below description about capturing the amounts. Nowhere in this description am I able to find that the amount is to be sent in cents. 

![2  Payments · checkout checkout sdk php Wiki](https://user-images.githubusercontent.com/11473888/62641804-7eaaeb00-b955-11e9-9544-163c1a502fcc.png)

However, as per your last suggestion we did the changes and it is working fine now. 

Thank you,
Reena
