### ISSUE TITLE
does SDK supports payment requests with source ids?

### ISSUE THREAD

**Issue by eventhorizonpl** [checkout/checkout-sdk-php#39]
Hi,

I've got a question related to card source ids.

In https://docs.checkout.com/docs/use-an-existing-card there is an information that I can use a source id for transaction.

I'm trying to use 'src_ujfjtv6arh3evdccwa5co2nhby' as $tokenId

$method = new TokenSource($tokenId);
$payment = new Payment($method, $currency);

but payments()->request($payment);

returns 'The endpoint did not accept the request. (Code: 422)'.

Should I use a different class for method?

Best regards,
Michal

**Comment by eventhorizonpl** [comment]
ok, I think I've found an answer
if (preg_match('/^tok_/', $tokenId)) {
            $method = new TokenSource($tokenId);
        } elseif (preg_match('/^src_/', $tokenId)) {
            $method = new IdSource($tokenId);
        }

**Comment by david-fiaty-cko** [comment]
@eventhorizonpl  yes that's the right approach indeed. A token source request will not work with an id source.

**Comment by david-fiaty-cko** [comment]
for more detailed error messages, you can use try/catch blocks and do the following:
try {
// Your request code
}
catch (\Exception $e) {
    echo $e->getBody();
}
