### ISSUE TITLE
Use https://docs.checkout.com/docs/get-payment-details with SDK

### ISSUE THREAD

**Issue by djoo** [checkout/checkout-sdk-php#45]
Hi,

I want to check a payment after a 3DSecure Challenge : https://docs.checkout.com/docs/get-payment-details

Is it possible to do this with this SDK ? 

Thanks

**Comment by aquila-freitas-cko** [comment]
Hi @djoo ,
Yes, it's very simple to get payment details with the SDK. The following line will do it for you.

```$details = $checkout->payments()->details('payment_id_goes_here');```


Feel free to reopen the issue if this is not the answer you're looking for.
