### ISSUE TITLE
finding issue to generate tokens by using test debit cards

### ISSUE THREAD

**Issue by ramantripathi** [checkout/checkout-sdk-php#48]
$checkout = new CheckoutApi($secretKey);
$card = new Card('4543 4740 0224 9996', 10, 2025);
$card->cvv = 100;
$token = $checkout->tokens()->request($card);

Fatal error: Uncaught exception 'Checkout\Library\Exceptions\CheckoutHttpException' with message 'The endpoint did not accept the request. (Code: 401)' in /home/bmain/public_html/GameOfTrades_11284/checkout-lib/src/Library/HttpHandler.php:327

**Comment by aquila-freitas-cko** [comment]
Hi @ramantripathi ,
We recommend not using token generation as it will be removed from the SDK in future versions. If you still want to use this, contact support@checkout.com to see if you have full card API enabled; you will also need to provide public key like `new CheckoutApi($secretKey, $sandbox, $publicKey);`
