### ISSUE TITLE
Notice: Undefined variable: paymentToken...

### ISSUE THREAD

**Issue by RiadFehric** [checkout/checkout-sdk-php#49]
Hi there!

I'm facing an issue while trying to proccess the credit card payment. I made a vardump in my procces payment file and I got this error:

**Notice: Undefined variable: paymentToken in /home/my_domain_name/process_checkout.php on line 8
NULL**

The funny thing is that this code is working perfectly on the other domain but when I copied the code to another domain it gives me the error mentioned above. I've changed the API keys of course...

I'm using PHP SDK and the both domains are on sandbox still.

Could anyone help please?

Thanks!

![chckout](https://user-images.githubusercontent.com/63100417/78351078-87b49080-75a6-11ea-8172-09f00a90e642.jpg)
![chckout-token-edited](https://user-images.githubusercontent.com/63100417/78351213-bcc0e300-75a6-11ea-8046-2df8385b56b9.jpg)

**Comment by nicolas-maalouf-cko** [comment]
Hi,

Can you please provide more details about the functions you're calling inside process_checkout.php ?
