### ISSUE TITLE
Default value for sandbox parameter is confusing

### ISSUE THREAD

**Issue by nikunjkotecha** [checkout/checkout-sdk-php#54]
https://github.com/checkout/checkout-sdk-php/blob/298cb2b6a7880ec9490f72511adc23fa62aa44f9/src/CheckoutApi.php#L154

It should be boolean even for default value.

**Comment by aquila-freitas-cko** [comment]
Hey @nikunjkotecha ,
I understand the confusion, please see #42 for the explanation. We do intend to improve this on the next version.

**Comment by nikunjkotecha** [comment]
thanks @aquila-freitas-cko for the explanation and my bad I didn't look for existing tickets (may be I checked only the open ones).

Just wanted to add - there is a trend in having the code readonly on production, so if we use this as library and it resides in vendor directory, we won't be able to write anything to the server, so using it from ini files usually won't work and having a default to read it from ini seems to be creating the problem in such cases.
