### ISSUE TITLE
How can i create customers and add payment meathods

### ISSUE THREAD

**Issue by Vikrant659** [checkout/checkout-sdk-php#55]
Hi, I was just checking the PHP sdk and I'm unable to find the API for how can i create a customer while creating a payment and how can i add multiple payment source(i.e. multiple cards) to a single customer using this sdk.

Thanks

**Comment by aquila-freitas-cko** [comment]
Hi @Vikrant659 ,
A customer is automatically created if you send customer details along with your payment request. You will receive a customer ID in the response that can be seen in the Hub. To save multiple cards, you need to perform a payment request for each card and keep their source ID.

Let me know if this answers your question. Please, check out [API Reference](https://api-reference.checkout.com/#tag/Payments/paths/~1payments/post) and [Documentation](https://docs.checkout.com/quickstart/use-an-existing-card) to learn more.
