### ISSUE TITLE
The endpoint did not accept the request. (Code: 422)

### ISSUE THREAD

**Issue by slicksenses** [checkout/checkout-sdk-php#64]
What about it. How will I be able to get rid of the error?

**Comment by nicolas-maalouf-cko** [comment]
Hi, please provide the sample request you're sending

**Comment by slicksenses** [comment]
> Hi, please provide the sample request you're sending
![Screen Shot 2020-12-15 at 7 58 41 PM](https://user-images.githubusercontent.com/71860791/102212392-1a684600-3f10-11eb-94a0-ff683b2b8094.png)

**Comment by slicksenses** [comment]
![Screen Shot 2020-12-15 at 8 01 42 PM](https://user-images.githubusercontent.com/71860791/102212545-5c918780-3f10-11eb-84e3-bd6ee692dc5d.png)
Here is the request from the form.
Thank you!

**Comment by slicksenses** [comment]
> Hi, please provide the sample request you're sending
I have tried to console log each line of the code. The error triggers on the $checkout->payments()->request ....The error shows (The endpoint did not accept the request. (Code: 422))

**Comment by nicolas-maalouf-cko** [comment]
Hi @slicksenses 
Please use amounts without decimals as described here:
https://docs.checkout.com/resources/calculating-the-value

So for £26.5 you should send 2650

I also noticed that the amount is gathered from the frontend, are you doing validations of the amount from the backend side in case a fraudster tries to change the amount from the frontend for example?

**Comment by slicksenses** [comment]
> Hi @slicksenses
> Please use amounts without decimals as described here:
> https://docs.checkout.com/resources/calculating-the-value
> 
> So for £26.5 you should send 2650
> 
> I also noticed that the amount is gathered from the frontend, are you doing validations of the amount from the backend side in case a fraudster tries to change the amount from the frontend for example?

Yeah it is. I don't have validations yet. 
I have tried changing the calculating value and it's working.
Thank you very much
