### ISSUE TITLE
Undefined function varnotification()

### ISSUE THREAD

**Issue by vvdenisov** [checkout/checkout-sdk-php#72]
https://github.com/checkout/checkout-sdk-php/blob/81c6aa884fb586b8a9456aecf83b639fed205f86/examples/Events/types.php#L32

**Comment by rsaestrela** [comment]
Hi @vvdenisov. We've just updated the codebase and released version 2.0.0-beta3 that contains a new instantiation layer, compatibility with different API Keys, support for OAuth, custom logging & http client and some other interesting features.

To get started, please have a look on the project documentation (README). In the next days, we will upload [extensive docs](https://github.com/checkout/checkout-sdk-php#exception-handling) on how to use each operation. Feel free to create an issue if you have any questions or difficulties migrating to the new version.
