### ISSUE TITLE
isPending() usage in Details request

### ISSUE THREAD

**Issue by abdelrahman-iaaly-cko** [checkout/checkout-sdk-php#75]
The isPending() function as defined in the Payment.php relies on the http status code to be `202`
https://github.com/checkout/checkout-sdk-php/blob/81c6aa884fb586b8a9456aecf83b639fed205f86/src/Models/Payments/Payment.php#L130-L133

However this model is used in the response to the `Details` API here:
https://github.com/checkout/checkout-sdk-php/blob/81c6aa884fb586b8a9456aecf83b639fed205f86/src/Controllers/PaymentController.php#L98-L104

I had a case where a merchant was relying on that function and had some unexpected issues, considering the result of `isPending()` as an answer to if the payment status itself is Pending.

Would it be a good idea to do a different model to parse the Details API response?

**Comment by rsaestrela** [comment]
Hi @abdelrahman-iaaly-cko. We've just updated the codebase and released version 2.0.0-beta3 that contains a new instantiation layer, compatibility with different API Keys, support for OAuth, custom logging & http client and some other interesting features.

For usage simplicity, all operations including Payments client `getPaymentDetails`, return the deserialized response payload in a array of properties. On a non 2xx API response, a CheckoutApiException is thrown.

To get started, please have a look on the project documentation (README). In the next days, we will upload [extensive docs](https://github.com/checkout/checkout-sdk-php#exception-handling) on how to use each operation. Feel free to create an issue if you have any questions or difficulties migrating to the new version.
