### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by david-fiaty** [checkout/checkout-sdk-php#76]
The first line of the readme file states:
**The Checkout SDK for PHP enables developers to easily work with Checkout.com APIs. It requires PHP 5.6.**
This could be misleading for users looking for the PHP 7 series.

**Comment by rsaestrela** [comment]
Hi @david-fiaty. We've just updated the codebase and released version 2.0.0-beta3 that contains a new instantiation layer, compatibility with different API Keys, support for OAuth, custom logging & http client and some other interesting features.

The new codebase README.md documents that this SDK is compatible with ant PHP version >= 7.4.

To get started, please have a look on the project documentation (README). In the next days, we will upload [extensive docs](https://github.com/checkout/checkout-sdk-php#exception-handling) on how to use each operation. Feel free to create an issue if you have any questions or difficulties migrating to the new version.
