### ISSUE TITLE
TokenSource() function issue 

### ISSUE THREAD

**Issue by hafiz44** [checkout/checkout-sdk-php#78]
hello,
I have installed checkut-SDK in my Laravel application but I am stuck with the TokenSource. In my scenario, the User submits a request to book the home I have to save user card details and use them when the admin accepts the request. Please see the following line where I need to put CardToken, mostly this token is being created from JS, but in my case I can't use the JS. I want to fetch data from DB and send request from the controller. In simple words, I cannot use Frames here in my scenario.

$method = new TokenSource('tok_rn3njn7dnbrefbu23zhbqqjeay');

Anyone, please suggest the solution for that, I badly need this.

**Comment by rsaestrela** [comment]
Hi @hafiz44. We've just updated the codebase and released version 2.0.0-beta3 that contains a new instantiation layer, compatibility with different API Keys, support for OAuth, custom logging & http client and some other interesting features.

The new codebase Payments client is 100% compatible with the API reference and it should be straightforward to implement your use case. This is how you can request a Token sourced payment:

```
  $requestTokenSource = new RequestTokenSource();
  $requestTokenSource->token = "tok_rn3njn7dnbrefbu23zhbqqjeay";

  $paymentRequest = new PaymentRequest();
  $paymentRequest->source = $requestTokenSource;

  $paymentResponse = $api->getPaymentsClient()->requestPayment($paymentRequest);
``` 

To get started, please have a look on the project documentation (README). In the next days, we will upload [extensive docs](https://github.com/checkout/checkout-sdk-php#exception-handling) on how to use each operation. Feel free to create an issue if you have any questions or difficulties migrating to the new version.
