### ISSUE TITLE
Regarding Mada payments

### ISSUE THREAD

**Issue by ali-alharthi** [checkout/checkout-sdk-php#79]
Hey!
Just out of curiosity, should I manage Mada payments outside of this package?
In another words can this package implement Mada payments?

The only thing I see different from other payment methods is that Mada require the following:
- A check against a fairly small list of BINs  - the bank identification number (BIN) - using the first six digits of the card. 
- Enforce `3ds.enabled` to `true` & `metadata.udf1` to `mada`.
- Lastly, `capture` or `capture_on` should be omitted from the request since mada only support purchases and refunds (no authorization or void).

I thought about adding a new payment within `Models/Payments`, but I have never used this package before nor have I checked the code deeply.
Therefore, the real question is does the payments that extend `Models/Payments/Payment` can customize or manipulate the request in anyway?

If so, I think I can integrate Mada after looking into the code a little more!
To be honest, I asked this because if it would require too much work I would prefer not to use the package and try to build a simple solution using Guzzle since that would integrate nicely with our code.

**Comment by rsaestrela** [comment]
Hi @ali-alharthi. We've just updated the codebase and released version 2.0.0-beta3 that contains a new instantiation layer, compatibility with different API Keys, support for OAuth, custom logging & http client and some other interesting features.

The new codebase Payments client is 100% compatible with the API reference and it should be straightforward to implement your use case. Here's a glimpse on how you can request a 3ds payment:

```
$requestCardSource = new RequestCardSource();
$requestCardSource->name = "name"
$requestCardSource->number = "number"
$requestCardSource->expiry_year = 2026
$requestCardSource->expiry_month = 12
$requestCardSource->cvv = 123

$threeDsRequest = new ThreeDsRequest();
$threeDsRequest->enabled = true;
$threeDsRequest->attempt_n3d = false;
$threeDsRequest->eci = "";
$threeDsRequest->cryptogram = "";
$threeDsRequest->xid = "";
$threeDsRequest->version = "2.0.1";

$paymentRequest = new PaymentRequest();
$paymentRequest->source = $requestCardSource ;
$paymentRequest->three_ds = $threeDsRequest;

$paymentResponse = $api->getPaymentsClient()->requestPayment($paymentRequest);
``` 

To get started, please have a look on the project documentation (README). In the next days, we will upload [extensive docs](https://github.com/checkout/checkout-sdk-php#exception-handling) on how to use each operation. Feel free to create an issue if you have any questions or difficulties migrating to the new version.
