### ISSUE TITLE
Event documentation outdated

### ISSUE THREAD

**Issue by christian-ehmig** [checkout/checkout-sdk-php#85]
https://github.com/checkout/checkout-sdk-php/wiki/5.-Events

The events endpoint currently supports the actions create, load, notification, retrieve, types, webhook.
These are not described correctly in the event docs.

**Comment by rsaestrela** [comment]
Hi @christian-ehmig. We've just updated the codebase and released version 2.0.0-beta3 that contains a new instantiation layer, compatibility with different API Keys, support for OAuth, custom logging & http client and some other interesting features.

To get started, please have a look on the project documentation (README). In the next days, we will upload [extensive docs](https://github.com/checkout/checkout-sdk-php#exception-handling) on how to use each operation. Feel free to create an issue if you have any questions or difficulties migrating to the new version.
