### ISSUE TITLE
Checkout token for a given Apple Pay token does not contains the "scheme" attribute

### ISSUE THREAD

**Issue by marcelojuventino** [checkout/checkout-sdk-php#87]
Hi!

I'm trying to get a checkout token for an Apple Pay token using this:

```
$applePayTokenHeader = new ApplePayHeader($transactionId', $publicKeyHash, $ephemeralPublicKey');
$applePayToken = new ApplePay($version, $signature, $data, $applePayTokenHeader);
$this->checkoutApi->tokens()->request($applePayToken);
```

But the token received does not contains the "scheme" attribute as specified in the [main API](https://api-reference.checkout.com/#operation/requestAToken):

```
{
  "type": "applepay",
  "token": "tok_xpn7bku43soenctdlqgw2zbpk4",
  "expires_on": "2021-12-24T13:46:27Z",
  "expiry_month": 12,
  "expiry_year": 2023,
  "last4": "6544",
  "bin": "492483",
  "token_format": "cryptogram_3ds",
  "http_code": 201
}
```

Anybody knows why? What I'm doing wrong?

**Comment by rsaestrela** [comment]
Hi @simas-ccore. We've just updated the codebase and released version 2.0.0-beta3 that contains a new instantiation layer, compatibility with different API Keys, support for OAuth, custom logging & http client and some other interesting features.

The new codebase Token client is 100% compatible with the API reference and it should be straightforward to implement your use case. Please have a look on [tokens package](https://github.com/checkout/checkout-sdk-php/tree/master/lib/Checkout/Tokens), there you should be able to find all the classes to map your Apple Pay token request. Then, requesting a token should be simple as:

```
$api->getTokensClient()->requestWalletToken($applePayTokenRequest);
``` 

To get started, please have a look on the project documentation (README). In the next days, we will upload [extensive docs](https://github.com/checkout/checkout-sdk-php#exception-handling) on how to use each operation. Feel free to create an issue if you have any questions or difficulties migrating to the new version.
