### ISSUE TITLE
phpunit version in require-dev

### ISSUE THREAD

**Issue by AdrienBr** [checkout/checkout-sdk-php#93]
### Environment

* Checkout SDK version: 2.0.0-beta3
* Operating System and version: Debian 

### Description

The require-dev section of this SDK requires this version of phpunit :
`        "symfony/phpunit-bridge": "^6.0.0",`

This is a problem for us because we use Symfony 5.4 and therefore we cannot install your SDK

### Expected behavior

Could you try with this requirement : 

`        "symfony/phpunit-bridge": "^5.4|^6.0.0",`

### Possible solution

- [x] I may be able to implement this bug fix

**Comment by rsaestrela** [comment]
Hi @AdrienBr. Thanks for creating this issue and your contribution for this project.

Since "symfony/phpunit-bridge" is a `dev` dependency this shouldn't be a problem installing the SDK (composer install, doesn't fetch and use `require-dev` dependencies from dependencies defined in `require`). 

Your changes look correct and we would be happy to merge them, but we need to fully understand your use case first. Can you please share more details on the way you're integrating the SDK? Thanks!

**Comment by AdrienBr** [comment]
Hi @rsaestrela , thank you for your reply.

On our development environments, we use `composer install` because we need dev dependencies. The `--no-dev` option is only used when we build our application for production environments.

`composer install` will install our dependencies, and all the dependencies of all the packages we use as well. As far as I know, there is no way we can ignore the dev dependencies of the packages we use.

You can look at these popular packages to see how they handle this :

https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/composer.json
https://github.com/doctrine/orm/blob/2.11.x/composer.json

**Comment by rsaestrela** [comment]
Hi @AdrienBr. Just to clarify "composer install will install our dependencies, and all the dependencies of all the packages we use as well" - this is correct as it will download **your dependencies**,  **your dev-dependencies** and **Checkout SDK dependencies** defined in Checkout SDK `require` section. 

In Checkout SDK, `symfony/phpunit-bridge` is a Checkout SDK `require-dev` dependency, so it should not be installed in your project. Let's look at the following example:

```json
{
    "name": "checkout/custom-sdk-integration",
    "type": "library",
    "require": {
        "php": ">=7.4",
        "checkout/checkout-sdk-php": "2.0.0-beta3"
    }
}
```
Then:
```
composer install
````

Vendor folder:

![deps](https://user-images.githubusercontent.com/3053481/157259909-77d5f0e1-3122-41d9-b2ee-3db03ff46512.png)

It didn't download `phpunit-bridge` or any other Checkout `require-dev` dependency. Please let me know what do you think, maybe I'm missing some detail. Thanks!
